### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ryan-hamblin** [Lambda-School-Labs/labs-spa-starter#2]
I've added a `__tests__` sub-directory to the `src` directory. I've seen this done a bunch, but I've also seen people add a `tests` director as a sibling to the `src` directory. 

I have no preference but we should standardize either way.

**Comment by AlexEntrepreneur** [comment]
What would you say are the drawbacks of having a `__tests__` directory within each component folder? I have seen this done for reusability's sake.

**Comment by ryan-hamblin** [comment]
> What would you say are the drawbacks of having a `__tests__` directory within each component folder? I have seen this done for reusability's sake.

I kind of like just keeping all `tests` in their own directory.

**Comment by ryan-hamblin** [comment]
- At this time we have nearly 80% coverage in the scaffolding. There are a few known issues that are filed #14 that are blocking us from 100% coverage but there are ample examples in the app already that demonstrate well-known practices around the subject.
