### ISSUE TITLE
Add Cypress .spec.js handling to "lint-staged" script in package.json

### ISSUE THREAD

**Issue by gordoncaister** [Lambda-School-Labs/labs-spa-starter#49]
Eslint fails to run on commit once Cypress is installed because cypress tests use variables context and cy without defining them, which throws eslint for a loop.

Consider using something like
```
"lint-staged": {
    "**/*.js": [
      "eslint --fix --ignore-pattern '**/*.spec.js'",
      "prettier-eslint --write"
    ]
  },

```
or using the --ignore-path "/cypress/"

**Comment by tinomen** [comment]
I asked you to move this to the global eslintrc config file but I'm realizing that we likely don't want to turn off linting for tests. This is as valuable code as the features. @ryan-hamblin I'm only familiar with a few open source JS projects, have you seen any that ignore linting their tests?

**Comment by ryan-hamblin** [comment]
I definitely think we should lint the test files themselves, but not the testing output. "Example if the tests generate files don't lint those files".
